/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/articles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rest Articles */
    get: operations["rest_articles_api_articles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/articles/{article_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rest Article */
    get: operations["rest_article_api_articles__article_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rest Health */
    get: operations["rest_health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnalysisRecord */
    AnalysisRecord: {
      /** Agent Name */
      agent_name: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ArticleDetail */
    ArticleDetail: {
      /** Article Id */
      article_id: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
      /** Domain */
      domain: string | null;
      /**
       * Published At
       * Format: date-time
       */
      published_at: string;
      /**
       * Ingested At
       * Format: date-time
       */
      ingested_at: string;
      /** Slot */
      slot: string;
      /** Themes */
      themes: string[];
      /** Persons */
      persons: string[];
      /** Orgs */
      orgs: string[];
      /** Tone */
      tone: number | null;
      /** Word Count */
      word_count: number | null;
      /** Analyses */
      analyses: components["schemas"]["AnalysisRecord"][];
      /** Sources */
      sources: components["schemas"]["SourceRecord"][];
      /** Source Count */
      source_count: number;
    };
    /** ArticleSummary */
    ArticleSummary: {
      /** Article Id */
      article_id: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
      /** Domain */
      domain: string | null;
      /**
       * Published At
       * Format: date-time
       */
      published_at: string;
      /** Themes */
      themes: string[];
      /** Scores */
      scores?: {
        [key: string]: number;
      } | null;
      /**
       * Source Count
       * @default 1
       */
      source_count: number;
    };
    /**
     * FeedPage
     * @description REST /api/articles response (keyset pagination via next_before).
     */
    FeedPage: {
      /** Articles */
      articles: components["schemas"]["ArticleSummary"][];
      /** Next Before */
      next_before: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthStatus */
    HealthStatus: {
      /** Db */
      db: boolean;
      /** Last Published Slot */
      last_published_slot: string | null;
      /** Kafka */
      kafka: boolean;
    };
    /**
     * SourceRecord
     * @description One copy (URL) that carried the story (M2a).
     */
    SourceRecord: {
      /** Url */
      url: string;
      /** Domain */
      domain: string | null;
      /**
       * Published At
       * Format: date-time
       */
      published_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  rest_articles_api_articles_get: {
    parameters: {
      query?: {
        theme?: string | null;
        domain?: string | null;
        text?: string | null;
        time_from?: string | null;
        time_to?: string | null;
        limit?: number | null;
        before?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rest_article_api_articles__article_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        article_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rest_health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
    };
  };
}
